name: LaTeX Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        run: |
          apt-get update && apt-get install -y make
          latexmk -pdf -output-directory=build documento.tex

      - name: Check output
        run: test -f build/documento.pdf